version: '3.8'

services:
  thu-llm-proxy:
    container_name: thu-llm-proxy
    restart: unless-stopped
    build:
      context: .
      args:
        PROXY_PORT: ${PROXY_PORT:-11443}
    # Use network_mode: host when IP allowlist is needed
    # Uncomment the next line to use host networking mode:
    # network_mode: host
    ports:
      - "${PROXY_PORT:-11443}:${PROXY_PORT:-11443}"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./config/nginx.main.conf:/etc/nginx/nginx.conf:ro
      - ./config/filter_empty_chunks.lua:/usr/local/openresty/nginx/conf/filter_empty_chunks.lua:ro
    networks:
      - proxy-network

    environment:
      PROXY_PORT: ${PROXY_PORT:-11443}
      HOST_ADDRESS: ${HOST_ADDRESS:-localhost}
      # When using bridge mode, all requests will appear to come from Docker's internal network
      ALLOWLIST_CONFIG: ""
      # When using host mode, this can effectively restrict by real client IPs
      # ALLOWLIST_CONFIG: ${ALLOWLIST_CONFIG:-"allow 192.168.0.0/16; allow 10.0.0.0/8; deny all;"}

networks:
  proxy-network:
    driver: bridge